// Code generated by go generate; DO NOT EDIT.

package handler

func (r *ShortenerHandler) Reset() {
	if r == nil {
		return
	}

	r.service = nil

	r.baseURL = ""

	r.log = nil

	r.auditPub = nil

	r.deleteChan = nil

	r.stopChan = nil

	clear(r.batchPending)

	r.batchTicker = nil

}
