//go:generate go run .
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type fieldInfo struct {
	Name string
	Type string
	Code string
}

type structInfo struct {
	Package string
	Name    string
	Fields  []fieldInfo
}

const fileTemplate = `// Code generated by go generate; DO NOT EDIT.

package {{.Package}}
{{range .Structs}}
func (r *{{.Name}}) Reset() {
	if r == nil {
		return
	}
	{{range .Fields}}{{.Code}}{{end}}
}
{{end}}
`

const fieldTemplates = `{{define "pointer"}}	if r.{{.Name}} != nil {
		* r.{{.Name}} = *{{.Type}}{}
	}
	{{end}}

	{{define "channel"}}	r.{{.Name}} = nil
	{{end}}

	{{define "slice"}}	r.{{.Name}} = r.{{.Name}}[:0]
	{{end}}

	{{define "map"}}	clear(r.{{.Name}})
	{{end}}

	{{define "bool"}}	r.{{.Name}} = false
	{{end}}

	{{define "numeric"}}	r.{{.Name}} = 0
	{{end}}

	{{define "string"}}	r.{{.Name}} = ""
	{{end}}

	{{define "error"}}	r.{{.Name}} = nil
	{{end}}

	{{define "sync"}}	{{end}}

	{{define "interface"}}	if res, ok := interface{}(r.{{.Name}}).(interface{ Reset() }); ok {
		res.Reset()
	}
	{{end}}
`

// Initialize templates with sub-templates
var fileTpl *template.Template

func init() {
	var err error
	fileTpl = template.Must(template.New("file").Parse(fileTemplate))
	fileTpl, err = fileTpl.Parse(fieldTemplates)
	if err != nil {
		panic(err)
	}
}

func main() {
	root := "."
	pkgs, err := scanPackages(root)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Ошибка сканирования пакетов: %v\n", err)
		os.Exit(1)
	}

	for pkgPath, structs := range pkgs {
		if len(structs) == 0 {
			continue
		}
		if err := generateResetFile(pkgPath, structs); err != nil {
			fmt.Fprintf(os.Stderr, "Ошибка генерации для %s: %v\n", pkgPath, err)
			os.Exit(1)
		}
		fmt.Printf("Сгенерирован reset.gen.go для пакета %s (%d структур)\n", pkgPath, len(structs))
	}
}

func scanPackages(root string) (map[string][]structInfo, error) {
	result := make(map[string][]structInfo)

	filesByDir := make(map[string][]string)
	if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			base := filepath.Base(path)
			if base == ".git" || base == ".thclaws" || base == "vendor" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		dir := filepath.Dir(path)
		filesByDir[dir] = append(filesByDir[dir], path)
		return nil
	}); err != nil {
		return nil, err
	}

	for dir, files := range filesByDir {
		if strings.Contains(dir, "/cmd/reset") || strings.Contains(dir, "\\cmd\\reset") {
			continue
		}
		pkgName, structs := parsePackageStructs(dir, files)
		if len(structs) > 0 {
			result[dir] = structs
			for i := range result[dir] {
				result[dir][i].Package = pkgName
			}
		}
	}

	return result, nil
}

func parsePackageStructs(dir string, files []string) (string, []structInfo) {
	fset := token.NewFileSet()
	var structs []structInfo
	var pkgName string

	for _, file := range files {
		f, err := parser.ParseFile(fset, file, nil, parser.ParseComments)
		if err != nil {
			continue
		}
		if pkgName == "" {
			pkgName = f.Name.Name
		}

		for _, decl := range f.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				if !hasGenResetComment(genDecl.Doc) {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				fields := extractFields(structType)
				structs = append(structs, structInfo{
					Name:   typeSpec.Name.Name,
					Fields: fields,
				})
			}
		}
	}

	return pkgName, structs
}

func hasGenResetComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}
	return false
}

func extractFields(st *ast.StructType) []fieldInfo {
	var fields []fieldInfo
	for _, field := range st.Fields.List {
		fieldType := exprToString(field.Type)

		for _, ident := range field.Names {
			name := ident.Name
			code := generateFieldCode(fieldType, name)
			fields = append(fields, fieldInfo{
				Name: name,
				Type: fieldType,
				Code: code,
			})
		}
	}
	return fields
}

func generateFieldCode(t, name string) string {
	var buf bytes.Buffer
	tplName := getResetTemplateName(t)
	if tplName == "sync" || tplName == "" {
		return ""
	}

	data := fieldInfo{Name: name, Type: t}
	if err := fileTpl.ExecuteTemplate(&buf, tplName, data); err != nil {
		return ""
	}
	return buf.String()
}

func exprToString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.StarExpr:
		return "*" + exprToString(e.X)
	case *ast.SelectorExpr:
		return exprToString(e.X) + "." + e.Sel.Name
	case *ast.ArrayType:
		return "[]" + exprToString(e.Elt)
	case *ast.MapType:
		return "map[" + exprToString(e.Key) + "]" + exprToString(e.Value)
	case *ast.InterfaceType:
		if len(e.Methods.List) == 0 {
			return "interface{}"
		}
		return "interface{}"
	case *ast.ChanType:
		return "chan " + exprToString(e.Value)
	case *ast.FuncType:
		return "func"
	default:
		return "interface{}"
	}
}

func getResetTemplateName(t string) string {
	switch {
	case strings.HasPrefix(t, "*"):
		innerType := strings.TrimPrefix(t, "*")
		if !strings.Contains(innerType, ".") && !isSyncType(innerType) {
			return "pointer"
		}
		return "channel"
	case strings.HasPrefix(t, "chan ") || t == "chan":
		return "channel"
	case strings.HasPrefix(t, "[]"):
		return "slice"
	case strings.HasPrefix(t, "map["):
		return "map"
	case strings.HasPrefix(t, "bool"):
		return "bool"
	case strings.HasPrefix(t, "int") || strings.HasPrefix(t, "uint") || strings.HasPrefix(t, "float") || strings.HasPrefix(t, "byte") || strings.HasPrefix(t, "rune"):
		return "numeric"
	case strings.HasPrefix(t, "string"):
		return "string"
	case t == "error":
		return "error"
	case strings.HasPrefix(t, "sync."):
		return "sync"
	default:
		if isBasicType(t) {
			return "sync"
		}
		return "interface"
	}
}

func generateResetFile(pkgPath string, structs []structInfo) error {
	data := struct {
		Package string
		Structs []structInfo
	}{
		Package: structs[0].Package,
		Structs: structs,
	}

	var buf bytes.Buffer
	if err := fileTpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("template execution failed: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "Предупреждение: форматирование не удалось: %v\n", err)
		formatted = buf.Bytes()
	}

	outFile := filepath.Join(pkgPath, "reset.gen.go")
	return os.WriteFile(outFile, formatted, 0644)
}

func isSyncType(typeName string) bool {
	syncTypes := map[string]bool{
		"WaitGroup": true,
		"Mutex":     true,
		"RWMutex":   true,
		"Cond":      true,
		"Pool":      true,
		"sync.Map":  true,
		"Once":      true,
	}
	if syncTypes[typeName] {
		return true
	}
	if strings.HasPrefix(typeName, "sync.") {
		base := strings.TrimPrefix(typeName, "sync.")
		return syncTypes[base]
	}
	return false
}

func isBasicType(t string) bool {
	basicTypes := []string{
		"bool", "byte", "complex", "error", "float",
		"int", "rune", "string", "uint", "uintptr",
	}
	tLower := strings.ToLower(t)
	for _, bt := range basicTypes {
		if strings.HasPrefix(tLower, bt) {
			return true
		}
	}
	return false
}
