//go:generate go run .
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

type fieldInfo struct {
	Name string
	Type string
}

type structInfo struct {
	Package string
	Name    string
	Fields  []fieldInfo
}

const genHeader = `// Code generated by go generate; DO NOT EDIT.

`

func main() {
	root := "."
	pkgs, err := scanPackages(root)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Ошибка сканирования пакетов: %v\n", err)
		os.Exit(1)
	}

	for pkgPath, structs := range pkgs {
		if len(structs) == 0 {
			continue
		}
		if err := generateResetFile(pkgPath, structs); err != nil {
			fmt.Fprintf(os.Stderr, "Ошибка генерации для %s: %v\n", pkgPath, err)
			os.Exit(1)
		}
		fmt.Printf("Сгенерирован reset.gen.go для пакета %s (%d структур)\n", pkgPath, len(structs))
	}
}

func scanPackages(root string) (map[string][]structInfo, error) {
	result := make(map[string][]structInfo)

	filesByDir := make(map[string][]string)
	if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			base := filepath.Base(path)
			if base == ".git" || base == ".thclaws" || base == "vendor" || base == "cmd" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		dir := filepath.Dir(path)
		filesByDir[dir] = append(filesByDir[dir], path)
		return nil
	}); err != nil {
		return nil, err
	}

	for dir, files := range filesByDir {
		pkgName, structs := parsePackageStructs(dir, files)
		if len(structs) > 0 {
			result[dir] = structs
			for i := range result[dir] {
				result[dir][i].Package = pkgName
			}
		}
	}

	return result, nil
}

func parsePackageStructs(dir string, files []string) (string, []structInfo) {
	fset := token.NewFileSet()
	var structs []structInfo
	var pkgName string

	for _, file := range files {
		f, err := parser.ParseFile(fset, file, nil, parser.ParseComments)
		if err != nil {
			continue
		}
		if pkgName == "" {
			pkgName = f.Name.Name
		}

		for _, decl := range f.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				if !hasGenResetComment(genDecl.Doc) {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				fields := extractFields(structType)
				structs = append(structs, structInfo{
					Name:   typeSpec.Name.Name,
					Fields: fields,
				})
			}
		}
	}

	return pkgName, structs
}

func hasGenResetComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}
	return false
}

func extractFields(st *ast.StructType) []fieldInfo {
	var fields []fieldInfo
	for _, field := range st.Fields.List {
		fieldName := fieldNames(field)
		fieldType := exprToString(field.Type)

		for _, name := range fieldName {
			fields = append(fields, fieldInfo{
				Name: name,
				Type: fieldType,
			})
		}
	}
	return fields
}

func fieldNames(field *ast.Field) []string {
	var names []string
	for _, n := range field.Names {
		names = append(names, n.Name)
	}
	return names
}

func exprToString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.StarExpr:
		return "*" + exprToString(e.X)
	case *ast.SelectorExpr:
		return exprToString(e.X) + "." + e.Sel.Name
	case *ast.ArrayType:
		return "[]" + exprToString(e.Elt)
	case *ast.MapType:
		return "map[" + exprToString(e.Key) + "]" + exprToString(e.Value)
	case *ast.InterfaceType:
		if len(e.Methods.List) == 0 {
			return "interface{}"
		}
		return "interface{}"
	case *ast.ChanType:
		return "chan " + exprToString(e.Value)
	case *ast.FuncType:
		return "func"
	default:
		return "interface{}"
	}
}

func generateResetFile(pkgPath string, structs []structInfo) error {
	var buf bytes.Buffer
	buf.WriteString(genHeader)
	buf.WriteString(fmt.Sprintf("package %s\n\n", structs[0].Package))

	for _, s := range structs {
		code, err := generateResetMethod(s)
		if err != nil {
			return fmt.Errorf("ошибка генерации метода %s: %w", s.Name, err)
		}
		buf.WriteString(code)
		buf.WriteString("\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "Предупреждение: форматирование не удалось: %v\n", err)
		formatted = buf.Bytes()
	}

	outFile := filepath.Join(pkgPath, "reset.gen.go")
	return os.WriteFile(outFile, formatted, 0644)
}

func generateResetMethod(s structInfo) (string, error) {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("func (r *%s) Reset() {\n", s.Name))
	buf.WriteString("if r == nil {\n")
	buf.WriteString("return\n")
	buf.WriteString("}\n\n")

	for _, field := range s.Fields {
		code := generateFieldReset(field)
		if code != "" {
			buf.WriteString(code)
		}
	}

	buf.WriteString("}\n")
	return buf.String(), nil
}

func generateFieldReset(f fieldInfo) string {
	t := f.Type

	// Указатели на структуры
	if strings.HasPrefix(t, "*") {
		innerType := strings.TrimPrefix(t, "*")
		if !strings.Contains(innerType, ".") && !isSyncType(innerType) {
			return fmt.Sprintf("if r.%s != nil {\n* r.%s = *%s{}\n}\n\n", f.Name, f.Name, innerType)
		}
		return fmt.Sprintf("r.%s = nil\n\n", f.Name)
	}

	// Каналы
	if strings.HasPrefix(t, "chan ") || t == "chan" {
		return fmt.Sprintf("r.%s = nil\n\n", f.Name)
	}

	// Слайсы
	if strings.HasPrefix(t, "[]") {
		return fmt.Sprintf("r.%s = r.%s[:0]\n\n", f.Name, f.Name)
	}

	// Мапы
	if strings.HasPrefix(t, "map[") {
		return fmt.Sprintf("clear(r.%s)\n\n", f.Name)
	}

	// Примитивы
	switch {
	case strings.HasPrefix(t, "bool"):
		return fmt.Sprintf("r.%s = false\n\n", f.Name)
	case strings.HasPrefix(t, "int") || strings.HasPrefix(t, "uint") || strings.HasPrefix(t, "float") || strings.HasPrefix(t, "byte") || strings.HasPrefix(t, "rune"):
		return fmt.Sprintf("r.%s = 0\n\n", f.Name)
	case strings.HasPrefix(t, "string"):
		return fmt.Sprintf("r.%s = \"\"\n\n", f.Name)
	case t == "error":
		return fmt.Sprintf("r.%s = nil\n\n", f.Name)
	case strings.HasPrefix(t, "sync."):
		return ""
	default:
		if isBasicType(t) {
			return ""
		}
		return fmt.Sprintf(`if res, ok := interface{}(r.%s).(interface{ Reset() }); ok {
res.Reset()
}

`, f.Name)
	}
}

func isSyncType(typeName string) bool {
	syncTypes := map[string]bool{
		"WaitGroup": true,
		"Mutex":     true,
		"RWMutex":   true,
		"Cond":      true,
		"Pool":      true,
		"sync.Map":  true,
		"Once":      true,
	}
	if syncTypes[typeName] {
		return true
	}
	if strings.HasPrefix(typeName, "sync.") {
		base := strings.TrimPrefix(typeName, "sync.")
		return syncTypes[base]
	}
	return false
}

func isBasicType(t string) bool {
	basicTypes := []string{
		"bool", "byte", "complex", "error", "float",
		"int", "rune", "string", "uint", "uintptr",
	}
	tLower := strings.ToLower(t)
	for _, bt := range basicTypes {
		if strings.HasPrefix(tLower, bt) {
			return true
		}
	}
	return false
}
