// Code generated by go generate; DO NOT EDIT.

package service

func (r *Service) Reset() {
	if r == nil {
		return
	}

	if res, ok := interface{}(r.storage).(interface{ Reset() }); ok {
		res.Reset()
	}

}
